### ISSUE TITLE
Select a tool for integrating the smart contract to a frontend

### ISSUE THREAD

**Issue by patozavala** [patozavala/UZH-DAO#3]

**Comment by patozavala** [comment]
We need to research first to decide:
[FactoryDAO](https://www.factorydao.xyz/)
[Tally](https://www.tally.xyz/)
[OpenZeppelin](https://www.openzeppelin.com/)

**Comment by pheeling** [comment]
FactoryDAO: Hard to find information or guides. Possibly this gitlab is used:
https://gitlab.com/factorydao

**Comment by patozavala** [comment]
We will implement it
